client
dev {{ .Device }}                  # This option was peakup from the server config
proto {{ .Proto}}                # This option was peakup from the server config
remote {{ .ServerAddress }} {{ .OpenVpnServerPort }} {{ .Proto }}
resolv-retry infinite
user nobody              # This option was peakup from the server config
group nogroup            # This option was peakup from the server config
persist-tun
persist-key
remote-cert-tls server
cipher {{ .Cipher }}       # This option was peakup from the server config
auth {{ .Auth }}              # This option was peakup from the server config
auth-nocache
tls-client
{{ .RedirectGateway }}
verb 3
<ca>
{{ .Ca }}
</ca>
<cert>
{{ .Cert }}
</cert>
<key>
{{ .Key }}
</key>
<tls-crypt>
{{ .Ta }}
</tls-crypt>
#Auto generated by OpenVPN-UI v.0.9