management 0.0.0.0 2080

dev {{ .Device }}
port {{ .Port }}
proto {{ .Proto }}

topology {{ .OVConfigTopology }}
keepalive {{ .Keepalive }}
max-clients {{ .MaxClients }}

persist-key
persist-tun
explicit-exit-notify 1

user {{ .OVConfigUser }}
group {{ .OVConfigGroup }}

client-config-dir {{ .OVConfigClientConfigDir }}
ifconfig-pool-persist {{ .IfconfigPoolPersist }}

ca {{ .Ca }}
cert {{ .Cert }}
key {{ .Key }}
crl-verify {{ .Crl }}
dh {{ .Dh }}

{{ .TLSControlChannel }}
{{ .TLSMinVersion }}
{{ .TLSRemoteCert }}

cipher {{ .Cipher }}
ncp-ciphers {{ .OVConfigNcpCiphers }}

auth {{ .Auth }}

{{ .Server }}
{{ .Route }}
{{ .PushRoute }}
{{ .DNSServer1 }}
{{ .DNSServer2 }}
{{ .RedirectGW }}

log {{ .OVConfigLogfile }}
verb {{ .OVConfigLogVerbose }}
status {{ .OVConfigStatusLog }}
status-version {{ .OVConfigStatusLogVersion }}

{{ .CustomOptOne }}
{{ .CustomOptTwo }}
{{ .CustomOptThree }}

#Auto generated by OpenVPN-UI
