client
dev {{ .Device }}
proto {{ .Proto}}
remote {{ .ServerAddress }} {{ .OpenVpnServerPort }} {{ .Proto }}
resolv-retry infinite
user {{ .OVConfigUser }}
group nogroup
persist-tun
persist-key
remote-cert-tls server
cipher {{ .Cipher }}
auth {{ .Auth }}
auth-nocache
tls-client
{{ .RedirectGateway }}
verb 3
{{ .AuthUserPass }}
{{ .CustomConfOne }}
{{ .CustomConfTwo }}
{{ .CustomConfThree }}
<ca>
{{ .Ca }}
</ca>
<cert>
{{ .Cert }}
</cert>
<key>
{{ .Key }}
</key>
<tls-crypt>
{{ .Ta }}
</tls-crypt>
# Auto generated by OpenVPN-UI v.0.9.3