management 0.0.0.0 2080

port {{ .Port }}
proto {{ .Proto }}
dev {{ .Device }}

ca {{ .Ca }}
cert {{ .Cert }}
key {{ .Key }}

cipher {{ .Cipher }}
auth {{ .Auth }}
dh {{ .Dh }}
crl-verify {{ .Crl }}

server {{ .Server }}
route {{ .Route }}
ifconfig-pool-persist {{ .IfconfigPoolPersist }}
push "route {{ .PushRoute }}"
push "dhcp-option DNS {{ .DNSServer1 }}"
push "dhcp-option DNS {{ .DNSServer2 }}"

{{ .RedirectGW }}

keepalive {{ .Keepalive }}
max-clients {{ .MaxClients }}

persist-key
persist-tun

log {{ .OVConfigLogfile }}
verb {{ .OVConfigLogVerbose }}

topology {{ .OVConfigTopology }}

client-config-dir {{ .OVConfigClientConfigDir }}

ncp-ciphers {{ .OVConfigNcpCiphers }}

user {{ .OVConfigUser }}
group {{ .OVConfigGroup }}

status {{ .OVConfigStatusLog }}
status-version {{ .OVConfigStatusLogVersion }}

explicit-exit-notify 1

{{ .CustomOptOne }}
{{ .CustomOptTwo }}
{{ .CustomOptThree }}

#auto generated by OpenVPN-UI

